from operator import gt
import turtle
import math

screen = turtle.Screen()
screen.bgcolor("skyblue")

t = turtle.Turtle()
t.color("black")
t.shape("turtle")
t.speed(10)

def drawRectangle(t, width, height, color):
  t.fillcolor(color)
  t.begin_fill()
  t.forward(width)
  t.left(90)
  t.forward(height)
  t.left(90)
  t.forward(width)
  t.left(90)
  t.forward(height)
  t.left(90)
  t.end_fill()
  
def drawTriangle(t, length, color):
  t.fillcolor(color)
  t.begin_fill()
  t.forward(length)
  t.left(135)
  t.forward(length / math.sqrt(2))
  t.left(90)
  t.forward(length / math.sqrt(2))
  t.left(135)
  t.end_fill()
  
def drawParallelogram(t, width, height, color):
  t.fillcolor(color)
  t.begin_fill()
  t.left(30)
  t.forward(width)
  t.left(60)
  t.forward(height)
  t.left(120)
  t.forward(width)
  t.left(60)
  t.forward(height)
  t.left(90)
  t.end_fill()
  
def drawFourRays(t, length, radius):
  for i in range(4):
    t.penup()
    t.forward(radius)
    t.pendown()
    t.forward(length)
    t.penup()
    t.backward(length + radius)
    t.left(90)

# Draw and fill the front of the house
t.penup() 
t.goto(-150, -120)
t.pendown()
drawRectangle(t, 100, 110, "blue")

t.penup()
t.goto(-120, -120)
t.pendown()
drawRectangle(t, 40, 60, "lightgreen")

t.penup()
t.goto(-150, -10)
t.pendown()
drawTriangle(t, 100, "magenta")

t.penup()
t.goto(-50, -120)
t.pendown()
drawParallelogram(t, 60, 110, "yellow")

t.penup()
t.goto(-30, -60)
t.pendown()
drawParallelogram(t, 20, 30, "brown")

t.penup()
t.goto(-50, -10)
t.pendown()
t.fillcolor("orange")
t.begin_fill()
t.left(30)
t.forward(60)
t.left(105)
t.forward(100 / math.sqrt(2))
t.left(75)
t.forward(60)
t.left(105)
t.forward(100 / math.sqrt(2))
t.left(45)
t.end_fill()

t.penup() 
t.goto(100, -130)
t.pendown()
drawRectangle(t, 20, 40, "brown")

t.penup() 
t.goto(65, -90)
t.pendown()
drawTriangle(t, 90, "lightgreen")
t.penup() 
t.goto(70, -45)
t.pendown()
drawTriangle(t, 80, "lightgreen")
t.penup() 
t.goto(75, -5)
t.pendown()
drawTriangle(t, 70, "lightgreen")

t.penup() 
t.goto(55, 110)
t.fillcolor("yellow")
t.pendown()
t.begin_fill()
t.circle(24)
t.end_fill()

t.penup()
t.goto(55, 134)
t.pendown()
drawFourRays(t, 25, 24)
t.right(45)
drawFourRays(t, 15, 24)
t.left(45)

t.color("black")
t.penup()
t.goto(-150, 70)
t.pendown()
t.write("House", None, None, "14pt bold")
t.penup()
t.goto(150, -150)
t.pendown()
t.write("Tree", None, None, "14pt bold")
t.penup()
t.goto(130, 150)
t.pendown()
t.write("Sun", None, None, "14pt bold")

t.penup()
t.goto(-100, -150)
t.left(90)
